# Build Stage
FROM --platform=linux/amd64 ubuntu:20.04 as builder
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y bmake gcc

COPY . /kgt
WORKDIR /kgt
RUN bmake -r install PREFIX=/install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
